version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus-configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-configs:/etc/prometheus/alerts
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:8.2.1
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./custom.ini:/etc/grafana/grafana.ini
    depends_on:
      - prometheus

  proxy-manager:
    image: justmark0/proxymanager:latest
    network_mode: "host"

  proxymanager-front:
    image: justmark0/proxymanager-front:latest
    ports:
      - "80:3000"

volumes:
  grafana-data:
