version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:8.2.1
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards/:/etc/grafana/provisioning/dashboards/
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
    depends_on:
      - prometheus

  proxy-manager:
    image: justmark0/proxymanager:latest
    network_mode: "host"
    volumes:
      - ./proxy_manager/settings.json:/app/settings.json
    environment:
      CHECK_AUTH: False

  proxymanager-front:
    image: justmark0/proxymanager-front:latest
    ports:
      - "10000:3000"
    depends_on:
      - proxy-manager

  exporter:
    image: justmark0/microexporter:latest
    ports:
      - "60123:60123"
    environment:
      AUTH_TOKEN: {{exporter_auth_token}}

volumes:
  grafana-data:

{% if use_docker_network %}
# external network for other containters to join, so they will be not available from web.
networks:
  default:
    name: microinfra_net
    external: true
{% endif %}
