version: '3.8'

services:
  microinfra_generator_backend:
    build: .
    environment:
      VIRTUAL_PORT: "8085"
      VIRTUAL_HOST: "api.microinfra.justmark0.me"
      LETSENCRYPT_HOST: "api.microinfra.justmark0.me"
      LETSENCRYPT_EMAIL: "developer@justmark0.me"
    networks:
      - web


networks:
  web: # external network for hostname access
    external:
      name: web
