groups:
- name: Encryption-Attack-Detection
  rules:
  - alert: HighDiskUsage
    expr: 100 * (node_filesystem_size_bytes{fstype="ext4"} - node_filesystem_free_bytes{fstype="ext4"}) / node_filesystem_size_bytes{fstype="ext4"} > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High disk usage detected
      description: The disk usage on {{ $labels.instance }} has been above 80% for the past 5 minutes. This may indicate a ransomware attack.

  - alert: HighWriteIOPS
    expr: rate(node_disk_write_time_seconds_total[5m]) > 5
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: High write IOPS detected
      description: The number of write IOPS on {{ $labels.instance }} has been above 5 per second for the past 2 minutes. This may indicate ransomware activity.

  - alert: HighDiskWriteUsage
    expr: (node_disk_write_bytes_total{job="node"} - node_disk_write_bytes_total{job="node"} offset 5m) / 300 > 1000
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: High Disk Write Usage Detected
      description: High disk write usage detected on {{ $labels.instance }}. This could be a sign of an encryption attack.

  - alert: DiskReadWriteRateAnomaly
    expr: rate(node_disk_reads_completed_total[5m]) + rate(node_disk_writes_completed_total[5m]) > 1000
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: 'Instance {{ $labels.instance }} has an unusual disk read/write rate'
      description: 'Unusual disk read/write rate on {{ $labels.instance }}'

  - alert: HostUnusualDiskReadRate
    expr: sum by (instance) (rate(node_disk_read_bytes_total[2m])) / 1024 / 1024 > 50
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Host unusual disk read rate (instance {{ $labels.instance }})
      description: "Disk is probably reading too much data (> 50 MB/s)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: HostUnusualDiskWriteRate
    expr: sum by (instance) (rate(node_disk_written_bytes_total[2m])) / 1024 / 1024 > 50
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host unusual disk write rate (instance {{ $labels.instance }})
      description: "Disk is probably writing too much data (> 50 MB/s)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: DiskInodesUnusialCreation
    expr: increase(node_disk_written_bytes_total[1m]) > 1000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Disk write spike detected"
      description: "Disk write rate on instance {{ $labels.instance }} has spiked to over 1000 bytes per second in the last 1 minute"

  - alert: FileExtensionChanged
    expr: changes(file_extension_changed[1m]) > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "File extensions within folder have changed"
      description: "File extensions within the folder have changed in the last 1 minute on instance {{ $labels.instance }}"

  - alert: FileModificationTimeChanged
    expr: changes(file_modification_time_changed[1m]) > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "File modification time has changed"
      description: "Modification time of the file has changed in the last 1 minute on instance {{ $labels.instance }}"

  - alert: NewProcessCreated
    expr: count(process_open_fds) by (process_name) > count(process_open_fds offset 1m) by (process_name)
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: New process created
      description: A new process has been created on {{ $labels.instance }} in the past 5 minutes. This may indicate the presence of ransomware.

  - alert: HighCPUUsage
    expr: 100 * (rate(node_cpu_seconds_total{mode="user"}[5m]) + rate(node_cpu_seconds_total{mode="system"}[5m])) / count(node_cpu_seconds_total{mode="system"}) > 90
    for: 1m
    labels:
        severity: critical
    annotations:
        summary: High CPU usage detected
        description: The CPU usage on {{ $labels.instance }} has been above 90% for the past minute. This may indicate ransomware running resource-intensive processes.

  - alert: TooManyDNSRequests
    expr: sum by(server, zone) (coredns_dns_requests_total) > 1000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Too many DNS requests for {{ $labels.server }}/{{ $labels.zone }}
      description: The number of DNS requests for {{ $labels.server }}/{{ $labels.zone }} has been consistently high for the past 5 minutes.
